# Series:
alert:
  PubNub: {'pubkey':'asdf', 'subkey':'sfdsdf'}
HPCGdir: '../hpcg'
outDir: '../out'
verbosity: 1
series:
  - name: First test
    abbrv: FTest
    nx: 16
    ny: 16
    nz: 16
    time: 10
    platform: Xen
    configuration: Linux_MPI
    repetitions: 1
    mpiargs:  --hostfile hostfile --mca btl_tcp_if_include 192.168.178.0/24
    runs:
      - NbrOfCores: 2
      - NbrOfCores: 4
      - NbrOfCores: 8
      - NbrOfCores: 12
      - NbrOfCores: 16
    viz:
      param1: 'NbrOfCores'
    